import { ClientBrand, Equipment, Profile, Production, ProjectCase, VerticalItem } from './types';

export const CLIENT_BRANDS: ClientBrand[] = [
  { id: '1', name: 'BYD - DENZA', sector: 'Automotivo Elétrico Premium', logoUrl: '/clients/byd.png' },
  { id: '2', name: 'METRÓPOLES', sector: 'Mídia & Jornalismo', logoUrl: '/clients/metropoles.svg' },
  { id: '3', name: 'BRB', sector: 'Banco de Brasília', logoUrl: '/clients/brb.png' },
  { id: '4', name: 'CAIXA ECONÔMICA', sector: 'Instituição Financeira Federal', logoUrl: '/clients/caixa.svg' },
  { id: '5', name: 'BANCO DO BRASIL', sector: 'Financeiro & Agronegócio', logoUrl: '/clients/banco-do-brasil.png' },
  { id: '6', name: 'UNICEF', sector: 'Organização Humanitária Global', logoUrl: '/clients/unicef.svg' },
  { id: '7', name: 'C6 BANK', sector: 'Fintech & Banco Digital', logoUrl: '/clients/c6bank.svg' },
  { id: '8', name: 'BALI PARK', sector: 'Entretenimento & Turismo', logoUrl: '/clients/bali.svg' },
  { id: '9', name: 'DENISE ZUBA', sector: 'Arquitetura & Design de Luxo', logoUrl: '/clients/denise-zuba.svg' },
  { id: '10', name: 'TECNA', sector: 'Engenharia & Construtora', logoUrl: '/clients/tecna.png' },
  { id: '11', name: 'CASSI', sector: 'Saúde & Planos Corporativos', logoUrl: '/clients/cassi.png' },
  { id: '12', name: 'ALBERO PIZZERIA', sector: 'Gastronomia & Pizzaria Artesanal', logoUrl: '/clients/albero.png' },
  { id: '13', name: 'ESCOLA DAS NAÇÕES (EDN)', sector: 'Educação Internacional Bilíngue', logoUrl: '/clients/edn.png' },
  { id: '14', name: 'EMPLAVI', sector: 'Incorporadora & Imóveis Alto Padrão', logoUrl: '/clients/emplavi.svg' },
  { id: '15', name: 'APRENDE BRASIL', sector: 'Sistema Educacional', logoUrl: '/clients/aprende.png' },
  { id: '16', name: 'BANCORBRÁS', sector: 'Consórcios & Turismo Corporativo', logoUrl: '/clients/bancorbras.png' },
  { id: '17', name: 'WEOOH', sector: 'Mídia Out-Of-Home & Painéis Digitais', logoUrl: '/clients/weooh.png' },
];

export const VERTICALS: VerticalItem[] = [
  {
    id: 'v1',
    slug: 'casamentos',
    title: 'Casamentos & Celebrações Exclusivas',
    subtitle: 'Cinema afetivo, luz orgânica e emoção pura',
    description: 'Documentamos histórias de amor com olhar autoral e cinematográfico. Sem poses artificiais: capturamos a espontaneidade, as lágrimas discretas e a energia contagiante de casamentos de luxo no Brasil e no exterior.',
    stats: 'Mais de 120 casamentos eternizados',
    camera_kit: 'Sony FX3 + Sony FX6 Cine Line • Lentes Sony GM F1.4 • Áudio Sound Devices',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-bride-and-groom-posing-in-a-forest-42416-large.mp4',
    clients: ['Casamentos Destino Trancoso', 'Villa Giardini Brasília', 'Punta del Este'],
  },
  {
    id: 'v2',
    slug: 'esportivo-automotivo',
    title: 'Esportivo & Alta Performance',
    subtitle: 'Velocidade, adrenalina e precisão aerodinâmica',
    description: 'Imagens que aceleram o batimento cardíaco. Filmagens dinâmicas com drones FPV de corrida, câmeras montadas em viaturas de perseguição e sensores de alta taxa de quadros (120fps/240fps) para capturar o ápice da engenharia e da potência esportiva.',
    stats: 'Filmagens em autódromos e circuitos fechados',
    camera_kit: 'RED Komodo-X 6K • Drones FPV Manuais • Estabilizador DJI Ronin 4D 6K',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-car-racing-on-a-curved-track-42792-large.mp4',
    clients: ['BYD - DENZA', 'Bali Park', 'Circuitos Automotivos'],
  },
  {
    id: 'v3',
    slug: 'arquitetura-interiores',
    title: 'Arquitetura & Design de Luxo',
    subtitle: 'Simetria, iluminação volumétrica e refinamento espacial',
    description: 'Transformamos concreto, luz e design em obras de arte audiovisuais. Empregamos movimentos fluídos com trilhos eletrônicos, lentes tilt-shift e pós-produção cromática milimétrica para construtoras e escritórios de arquitetura renomados.',
    stats: 'Mais de 80 mansões e empreendimentos filmados',
    camera_kit: 'Sony FX6 • Lentes Canon Cinema Tilt & Shift • Gimbals Pesados RS3 Pro',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-modern-apartment-interior-with-minimalist-furniture-41484-large.mp4',
    clients: ['Denise Zuba', 'Emplavi', 'Albero', 'Tecna'],
  },
  {
    id: 'v4',
    slug: 'corporativo-marcas',
    title: 'Grandes Marcas & Filmes Institucionais',
    subtitle: 'Posicionamento estratégico com escala cinematográfica',
    description: 'Filmes institucionais e comerciais publicitários que traduzem a grandeza de líderes de mercado. Da concepção de roteiro à finalização para veiculação nacional e digital, garantimos autoridade indiscutível.',
    stats: 'Campanhas veiculadas nacionalmente',
    camera_kit: 'RED Komodo-X + ARRI Amira • Lentes Anamórficas Atlas Orion • Iluminação Aputure 600d/1200d',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-city-buildings-at-sunset-41459-large.mp4',
    clients: ['Banco do Brasil', 'BRB', 'Caixa Econômica', 'C6 Bank', 'Metrópoles', 'WeOOH'],
  },
  {
    id: 'v5',
    slug: 'documentarios-impacto',
    title: 'Documentários & Causas Globais',
    subtitle: 'Vozes reais, narrativa humanizada e relevância mundial',
    description: 'Cinema documental com sensibilidade jornalística e estética de cinema verdade. Expedições de campo, cobertura de missões humanitárias e registros de impacto com agilidade e ética documental profunda.',
    stats: 'Expedições em 8 estados brasileiros',
    camera_kit: 'Sony FX6 Run-and-Gun • Lentes Zoom Cine Sony GM • Microfones Sennheiser MKH 416',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-soil-with-a-plant-growing-42790-large.mp4',
    clients: ['UNICEF', 'Cassi', 'Aprende Brasil', 'Bancorbrás'],
  },
];

export const PROJECT_CASES: ProjectCase[] = [
  {
    id: 'c1',
    title: 'O Futuro da Mobilidade Sustentável',
    client: 'BYD - DENZA',
    category: 'Automotivo',
    year: '2025',
    duration: '02:14 min',
    director: 'Felipe Villela Vieira',
    dop: 'Rodrigo Alves',
    thumbnail: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-car-racing-on-a-curved-track-42792-large.mp4',
    synopsis: 'Campanha de lançamento da linha Denza no Centro-Oeste. Filmado com RED Komodo-X em 6K anamórfico e drone FPV a mais de 140 km/h no Autódromo Internacional.',
    tags: ['Cinema Anamórfico', 'Drone FPV', 'Grading ACES'],
    camera_used: 'RED Komodo-X + Atlas Orion 40mm T2',
  },
  {
    id: 'c2',
    title: 'Vozes da Infância: Esperança nas Fronteiras',
    client: 'UNICEF',
    category: 'Documentário',
    year: '2025',
    duration: '05:40 min',
    director: 'Felipe Villela Vieira',
    dop: 'Rodrigo Alves',
    thumbnail: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1200&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-soil-with-a-plant-growing-42790-large.mp4',
    synopsis: 'Documentário sensível registrando missões humanitárias de acolhimento e nutrição infantil no Norte do Brasil. Luz estritamente natural e áudio de cinema direto.',
    tags: ['Documentário', 'Impacto Social', 'Cinema Verdade'],
    camera_used: 'Sony FX6 + Lentes Cine Prime 35mm & 50mm',
  },
  {
    id: 'c3',
    title: 'Elegância Mineral: Mansão dos Ventos',
    client: 'DENISE ZUBA ARQUITETURA',
    category: 'Arquitetura',
    year: '2025',
    duration: '03:05 min',
    director: 'Felipe Villela Vieira',
    dop: 'Gabriel Santos',
    thumbnail: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-modern-apartment-interior-with-minimalist-furniture-41484-large.mp4',
    synopsis: 'Exploração sensorial de 1.400 m² no Lago Sul. Uso de sliders computadorizados e contraluzes suaves no crepúsculo de Brasília para ressaltar texturas naturais.',
    tags: ['Arquitetura', 'High-End', 'Slow Motion 4K'],
    camera_used: 'Sony FX3 + DJI Ronin RS3 Pro + Canon TS-E 24mm',
  },
  {
    id: 'c4',
    title: 'Celebração Inesquecível na Villa Giardini',
    client: 'Casamento Sofia & Leonardo',
    category: 'Casamentos',
    year: '2024',
    duration: '06:12 min',
    director: 'Felipe Villela Vieira',
    dop: 'Lucas Mendes',
    thumbnail: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-bride-and-groom-posing-in-a-forest-42416-large.mp4',
    synopsis: 'Filme de casamento em 4K HDR com 4 câmeras sincronizadas via timecode sem fio. Trilha sonora original personalizada e edição rítmica arrebatadora.',
    tags: ['Wedding Film', 'Multicam 4K', 'Color Grading Luxo'],
    camera_used: 'Sony FX6 + FX3 Dual Rig + Lentes GM 50mm f/1.2',
  },
  {
    id: 'c5',
    title: 'A Nova Era do Crédito & Inovação',
    client: 'BANCO DO BRASIL',
    category: 'Corporativo',
    year: '2024',
    duration: '01:30 min',
    director: 'Felipe Villela Vieira',
    dop: 'Rodrigo Alves',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-city-buildings-at-sunset-41459-large.mp4',
    synopsis: 'Comercial institucional transmitindo solidez e dinamismo digital. Direção de arte contemporânea e composição de cena com mais de 30 figurantes.',
    tags: ['Institucional', 'Comercial TV', 'High Production Value'],
    camera_used: 'RED Komodo-X 6K + Cooke S4/i Prime Lenses',
  },
  {
    id: 'c6',
    title: 'Metrópoles: O Pulso da Notícia em Tempo Real',
    client: 'METRÓPOLES',
    category: 'Corporativo',
    year: '2024',
    duration: '02:00 min',
    director: 'Felipe Villela Vieira',
    dop: 'Gabriel Santos',
    thumbnail: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-urban-traffic-at-night-with-light-trails-41386-large.mp4',
    synopsis: 'Filme manifesto sobre o jornalismo digital mais acessado do país. Ritmo frenético, iluminação neon e gravação com drone de alta velocidade no centro do poder.',
    tags: ['Brand Manifesto', 'Drone FPV Noturno', 'Sound Design Heavy'],
    camera_used: 'DJI Inspire 3 Zenmuse X9-8K Air Cinema',
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-admin-1',
    email: 'diretoria@firstview.com.br',
    full_name: 'Felipe Villela Vieira',
    role: 'admin',
    position: 'Diretor Executivo & Head de Produção',
    phone: '+55 (61) 98123-4567',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    skills: ['Direção Geral', 'Roteiro & Produção', 'Color Grading ACES', 'Negociação Comercial'],
    is_active: true,
    active_shoots_count: 2,
  },
  {
    id: 'user-dop-2',
    email: 'rodrigo.dop@firstview.com.br',
    full_name: 'Rodrigo Alves',
    role: 'member',
    position: 'Diretor de Fotografia (DoP)',
    phone: '+55 (61) 99234-5678',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    skills: ['Cinematografia RED/ARRI', 'Iluminação de Cinema', 'Lentes Anamórficas', 'DRT Cinema'],
    is_active: true,
    active_shoots_count: 3,
  },
  {
    id: 'user-fpv-3',
    email: 'gabriel.drone@firstview.com.br',
    full_name: 'Gabriel Santos',
    role: 'member',
    position: 'Piloto de Drone FPV & Cinegrafista',
    phone: '+55 (61) 98345-6789',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    skills: ['Habilitado ANAC / DECEA', 'Piloto FPV Corrida', 'Inspire 3 Cinema', 'Gimbal RS3 Pro'],
    is_active: true,
    active_shoots_count: 1,
  },
  {
    id: 'user-editor-4',
    email: 'mariana.pos@firstview.com.br',
    full_name: 'Mariana Silveira',
    role: 'member',
    position: 'Editora Chefe & Colorista',
    phone: '+55 (61) 99456-7890',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    skills: ['DaVinci Resolve Studio', 'Premiere Pro', 'Sound Design 5.1', 'Motion Graphics After Effects'],
    is_active: true,
    active_shoots_count: 0,
  },
  {
    id: 'user-cam-5',
    email: 'lucas.cam@firstview.com.br',
    full_name: 'Lucas Mendes',
    role: 'member',
    position: 'Cinegrafista & Operador de Câmera',
    phone: '+55 (61) 98567-8901',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    skills: ['Operação de Câmera B', 'Foco / 1st AC', 'Áudio Direto', 'Iluminação Leve'],
    is_active: true,
    active_shoots_count: 2,
  },
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-1',
    name: 'RED Komodo-X 6K Cinema Camera',
    brand: 'RED Digital Cinema',
    model: 'Komodo-X 6K S35',
    serial_number: 'RED-KX-882109',
    category: 'camera',
    status: 'em_uso',
    current_holder_id: 'user-dop-2',
    current_holder_name: 'Rodrigo Alves',
    location_storage: 'Maleta Pelicase 1510 - Sala de Câmeras',
    daily_rate: 1800.00,
    notes: 'Acompanha 4x RED Pro CFexpress 1TB, 4x Baterias Micro V-Lock e módulo áudio RF.',
    last_maintenance_date: '2025-01-15',
  },
  {
    id: 'eq-2',
    name: 'Sony FX6 Cinema Line Full-Frame',
    brand: 'Sony',
    model: 'ILME-FX6V',
    serial_number: 'SNY-FX6-443102',
    category: 'camera',
    status: 'disponivel',
    current_holder_id: null,
    current_holder_name: null,
    location_storage: 'Armário A1 - Prateleira 2',
    daily_rate: 1200.00,
    notes: 'Firmware 5.0 atualizado. Sensor limpo em laboratório em fevereiro.',
    last_maintenance_date: '2025-02-10',
  },
  {
    id: 'eq-3',
    name: 'Sony FX3 Cinema Line Full-Frame (Rig Câmera B)',
    brand: 'Sony',
    model: 'ILME-FX3',
    serial_number: 'SNY-FX3-998721',
    category: 'camera',
    status: 'em_uso',
    current_holder_id: 'user-cam-5',
    current_holder_name: 'Lucas Mendes',
    location_storage: 'Mochila Manfrotto Pro Light',
    daily_rate: 750.00,
    notes: 'Com cage SmallRig, alça XLR e 6 baterias NP-FZ100.',
    last_maintenance_date: '2025-01-20',
  },
  {
    id: 'eq-4',
    name: 'Kit Lentes Anamórficas Atlas Orion (32mm, 50mm, 80mm)',
    brand: 'Atlas Lens Co.',
    model: 'Orion Series 2x Anamorphic T2.0',
    serial_number: 'ATL-ORN-SET-3',
    category: 'lente',
    status: 'em_uso',
    current_holder_id: 'user-dop-2',
    current_holder_name: 'Rodrigo Alves',
    location_storage: 'Maleta Estanque de Lentes Pelicase Vermelha',
    daily_rate: 2200.00,
    notes: 'Montagem PL nativa com adaptador Canon RF e Sony E-mount.',
    last_maintenance_date: '2024-12-05',
  },
  {
    id: 'eq-5',
    name: 'Kit Sony G Master F2.8 (16-35, 24-70, 70-200 GM II)',
    brand: 'Sony',
    model: 'FE G Master Trio Mark II',
    serial_number: 'SNY-GM-TRIO-07',
    category: 'lente',
    status: 'disponivel',
    current_holder_id: null,
    current_holder_name: null,
    location_storage: 'Armário A2 - Lentes Zoom',
    daily_rate: 900.00,
    notes: 'Todos os filtros ND PolarPro Peter McKinnon 82mm inclusos.',
    last_maintenance_date: '2025-01-30',
  },
  {
    id: 'eq-6',
    name: 'DJI Inspire 3 Cinema Drone 8K Full-Frame',
    brand: 'DJI',
    model: 'Inspire 3 + Zenmuse X9-8K Air',
    serial_number: 'DJI-INS3-554101',
    category: 'drone',
    status: 'reservado',
    current_holder_id: 'user-fpv-3',
    current_holder_name: 'Gabriel Santos',
    location_storage: 'Case Rígido com Rodas DJI - Sala Segura',
    daily_rate: 3500.00,
    notes: 'Registrado na ANAC. Inclui 6 pares de baterias TB51 e controle duplo RC Plus.',
    last_maintenance_date: '2025-02-18',
  },
  {
    id: 'eq-7',
    name: 'Drone FPV Cinemático 6S Long Range Custom',
    brand: 'GepRC / First View Custom',
    model: 'CineLog35 V2 HD O3 Air Unit',
    serial_number: 'FPV-FV-004',
    category: 'drone',
    status: 'disponivel',
    current_holder_id: null,
    current_holder_name: null,
    location_storage: 'Armário D1 - Drones FPV',
    daily_rate: 800.00,
    notes: 'Sintonizado para voos suaves e proximidade de veículos/noivos. Goggles 2 inclusos.',
    last_maintenance_date: '2025-02-01',
  },
  {
    id: 'eq-8',
    name: 'Luz Contínua Aputure LS 600d Pro Daylight',
    brand: 'Aputure',
    model: 'Light Storm 600d Pro',
    serial_number: 'AP-600D-019',
    category: 'luz',
    status: 'em_uso',
    current_holder_id: 'user-dop-2',
    current_holder_name: 'Rodrigo Alves',
    location_storage: 'Case Rígido Aputure + Tripé C-Stand Avenger',
    daily_rate: 550.00,
    notes: 'Acompanha Softbox Light Dome 150 e Fresnel F10.',
    last_maintenance_date: '2024-11-20',
  },
  {
    id: 'eq-9',
    name: 'Kit 4x Nanlite Pavotube II 30X RGBWW',
    brand: 'Nanlite',
    model: 'Pavotube II 30X 4-Kit',
    serial_number: 'NAN-PT30X-4K',
    category: 'luz',
    status: 'manutencao',
    current_holder_id: null,
    current_holder_name: null,
    location_storage: 'Bancada Técnica de Manutenção',
    daily_rate: 400.00,
    notes: 'Tubo 2 com conector USB-C de carregamento frouxo. Em conserto na assistência técnica.',
    last_maintenance_date: '2025-02-22',
  },
  {
    id: 'eq-10',
    name: 'Microfone Shotgun de Cinema Sennheiser MKH 416',
    brand: 'Sennheiser',
    model: 'MKH 416-P48U3',
    serial_number: 'SNN-MKH416-88',
    category: 'audio',
    status: 'disponivel',
    current_holder_id: null,
    current_holder_name: null,
    location_storage: 'Armário B1 - Áudio Profissional',
    daily_rate: 250.00,
    notes: 'Acompanha dirigível Rycote Windshield e vara de boom K-Tek de fibra de carbono.',
    last_maintenance_date: '2025-01-10',
  },
  {
    id: 'eq-11',
    name: 'Estabilizador Gimbal DJI RS 3 Pro Combo',
    brand: 'DJI',
    model: 'Ronin RS 3 Pro Combo',
    serial_number: 'DJI-RS3P-71209',
    category: 'estabilizador_suporte',
    status: 'em_uso',
    current_holder_id: 'user-cam-5',
    current_holder_name: 'Lucas Mendes',
    location_storage: 'Maleta EPP Preta',
    daily_rate: 350.00,
    notes: 'Inclui motor de foco LiDAR e transmissor RavenEye.',
    last_maintenance_date: '2025-01-25',
  },
];

export const INITIAL_PRODUCTIONS: Production[] = [
  {
    id: 'prod-1',
    title: 'Diária 1: Campanha Autódromo BYD Denza',
    client_name: 'BYD - DENZA',
    vertical: 'Esportivo & Automotivo',
    location: 'Autódromo Internacional Nelson Piquet / Eixo Monumental',
    start_time: '2026-09-22T06:00:00Z',
    end_time: '2026-09-22T18:30:00Z',
    status: 'confirmada',
    director_id: 'user-admin-1',
    director_name: 'Felipe Villela Vieira',
    notes: 'Captura de planos em alta velocidade ao nascer do sol e no fim da tarde (Golden Hour). Rádio comunicadores no canal 4.',
    crew: [
      { profile_id: 'user-admin-1', full_name: 'Felipe Villela Vieira', assigned_role: 'Diretor Geral' },
      { profile_id: 'user-dop-2', full_name: 'Rodrigo Alves', assigned_role: 'Diretor de Fotografia' },
      { profile_id: 'user-fpv-3', full_name: 'Gabriel Santos', assigned_role: 'Piloto Drone FPV' },
      { profile_id: 'user-cam-5', full_name: 'Lucas Mendes', assigned_role: 'Operador Câmera B (Car-to-car)' },
    ],
    equipment_ids: ['eq-1', 'eq-4', 'eq-7', 'eq-8', 'eq-11'],
  },
  {
    id: 'prod-2',
    title: 'Gravação Arquitetura: Residência Denise Zuba',
    client_name: 'DENISE ZUBA',
    vertical: 'Arquitetura & Interiores',
    location: 'Condomínio Ville de Montagne, Lago Sul, Brasília/DF',
    start_time: '2026-09-24T14:00:00Z',
    end_time: '2026-09-24T21:00:00Z',
    status: 'confirmada',
    director_id: 'user-admin-1',
    director_name: 'Felipe Villela Vieira',
    notes: 'Captação dos interiores com luz natural da tarde seguida por iluminação zenital no espelho d’água às 18h30.',
    crew: [
      { profile_id: 'user-admin-1', full_name: 'Felipe Villela Vieira', assigned_role: 'Diretor' },
      { profile_id: 'user-cam-5', full_name: 'Lucas Mendes', assigned_role: 'Operador Gimbal' },
    ],
    equipment_ids: ['eq-2', 'eq-5', 'eq-11'],
  },
  {
    id: 'prod-3',
    title: 'Casamento Real: Helena & Guilherme (Multicam)',
    client_name: 'Villa Giardini Eventos',
    vertical: 'Casamentos & Celebrações',
    location: 'Villa Giardini Ecoart - SHIS QI 23, Brasília/DF',
    start_time: '2026-09-27T13:00:00Z',
    end_time: '2026-09-28T02:00:00Z',
    status: 'planejamento',
    director_id: 'user-admin-1',
    director_name: 'Felipe Villela Vieira',
    notes: 'Cobertura completa com 3 câmeras e drone aéreo. Cerimônia ao ar livre às 16h45. Trilha em gravação multicanal.',
    crew: [
      { profile_id: 'user-admin-1', full_name: 'Felipe Villela Vieira', assigned_role: 'Diretor Executivo' },
      { profile_id: 'user-dop-2', full_name: 'Rodrigo Alves', assigned_role: 'Câmera A (Noiva)' },
      { profile_id: 'user-cam-5', full_name: 'Lucas Mendes', assigned_role: 'Câmera B (Noivo & Convidados)' },
      { profile_id: 'user-fpv-3', full_name: 'Gabriel Santos', assigned_role: 'Drone Aéreo & Câmera C' },
    ],
    equipment_ids: ['eq-2', 'eq-3', 'eq-5', 'eq-6', 'eq-10', 'eq-11'],
  },
];
